---
  - name: Installing Node Exporter
    hosts: "{{ variable_host | default('tag_Batch_43') }}"
    gather_facts: yes
    become: yes
    become_user: root
    vars:
      use_handler: false
      ansible_ssh_private_key_file: "/etc/ansible/ansiblekey.pem"
      ansible_user: ubuntu
    tasks:
       - name: Install net-tools
         shell: apt update && apt install -y net-tools

       - name: Check for 9100 Port
         shell: netstat -nltp | grep -i 9100
         register: output
         ignore_errors: yes
         
       - name: Download & Install Node Exporter
         shell: |
          sudo useradd --no-create-home --shell /bin/false node_exporter
          wget https://github.com/prometheus/node_exporter/releases/download/v1.3.1/node_exporter-1.3.1.linux-amd64.tar.gz -P /tmp
          cd /tmp
          tar xvf node_exporter-1.3.1.linux-amd64.tar.gz
          sudo cp /tmp/node_exporter-1.3.1.linux-amd64/node_exporter /usr/local/bin/
          sudo chown node_exporter:node_exporter /usr/local/bin/node_exporter
         when: output.rc != 0

       - name: Copy node_exporter.service file to destination folder.
         copy: >
            src=/root/ansiblecode/Playbooks/6.Dyanmic-Inventory/node_exporter.service
            dest=/lib/systemd/system/node_exporter.service
            owner=root
            group=root
            mode=0644
         when: output.rc != 0 or {{ use_handler }} == true
         # Use --extra-vars use_handler=true in the playbook deployment.
         notify:
            - Restart NodeExporter Service
    handlers:
    - name: Restart NodeExporter Service
      shell: |
       sudo systemctl daemon-reload
       sudo systemctl start node_exporter
       sudo systemctl restart node_exporter
       sudo systemctl enable node_exporter
       sudo systemctl status node_exporter --no-pager